# Generated by Django 3.2.6 on 2021-09-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_auto_20210919_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
