# Generated by Django 3.2.6 on 2021-09-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_post_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
    ]
